name: "Firebase Distribution"
inputs:
  flavor:
    required: true
    description: "Product Flavor (Develop, Production)"
  keystore-base64:
    required: true
  keystore-password:
    required: true
  keystore-alias:
    required: true
  keystore-key-password:
    required: true
  service-credential-base64:
    required: true

runs:
  using: "composite"
  steps:
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Decode Keystore
      run: echo -n "${{ inputs.keystore-base64 }}" | base64 --decode > app/release.keystore
      shell: bash
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    - name: Build
      run: ./gradlew assemble${{ inputs.flavor }}Release
      shell: bash
      env:
        ANDROID_KEYSTORE_PASSWORD: ${{ inputs.keystore-password }}
        ANDROID_KEYSTORE_ALIAS: ${{ inputs.keystore-alias }}
        ANDROID_KEYSTORE_KEY_PASSWORD: ${{ inputs.keystore-key-password }}
    - name: Decode Service Credential
      run: echo -n "${{ inputs.service-credential-base64 }}" | base64 --decode > service_credential.json
      shell: bash
    - name: Create Release Notes
      run: echo "${{ github.event.head_commit.message }}" >> release_notes.txt
      shell: bash
    - name: Firebase Distribute
      run: ./gradlew appDistributionUpload${{ inputs.flavor }}Release
      shell: bash
      env:
        APK_PATH: app/build/outputs/apk/${{ inputs.flavor }}/release/app-${{ inputs.flavor }}-release.apk
